### ISSUE TITLE
Division by 0 error on running game (OpenGL mode only)

### ISSUE THREAD

**Issue by nukebloodaxe** [mnalis/ironseed_fpc#26]
I've noticed the following behaviour in VirtualBox instances of:
Debian 10
SUSE Tumbleweed
UBUNTU 20.04

IronSeed v1.20.0016 fpc 0.0.5
ironseed      Copyright (C) 1994  Channel 7
ironseed_fpc  Copyright (C) 2013  y-salnikov
ironseed_fpc  Copyright (C) 2016  Nuke Bloodaxe
ironseed_fpc  Copyright (C) 2020  Matija Nalis
An unhandled exception occurred at $00007FDA533C26A4:
EDivByZero: Division by zero
  $00007FDA533C26A4

Fatal Run Error! 217

I normally test things in a virtual environment, so this is a big problem.  However, I've also noticed the original upstream build is now giving the same behaviour, so something has changed in the build environments concerned, or there is a recently introduced incompatibility in VirtualBox itself.  I will be running some tests against real environments soon and will update my findings here.

**Comment by nukebloodaxe** [comment]
Just sorted out an old laptop, Tumbleweed works in a real environment, so the error is probably VirtualBox specific.

**Comment by mnalis** [comment]
could you (on latest `master` branch) uncomment `debug` line in `Makefile` and recompile / rerun? (preferably in Debian Virtualbox instance, if it's all the same to you).
With any luck, it should give source code lines in which errors are happening

**Comment by nukebloodaxe** [comment]
I was expecting there ot be a bit more, after uncommenting the debug line, so I also ran it through gdb, but it's still outputting this:
(gdb) run
Starting program: /home/nukebloodaxe/mnalis/ironseed_fpc/is 
IronSeed v1.20.0016 fpc 0.0.6
ironseed      Copyright (C) 1994  Channel 7
ironseed_fpc  Copyright (C) 2013  y-salnikov
ironseed_fpc  Copyright (C) 2016  Nuke Bloodaxe
ironseed_fpc  Copyright (C) 2020  Matija Nalis
[Detaching after fork from child process 1945]
An unhandled exception occurred at $00007FFFEDB03460:
EDivByZero: Division by zero
  $00007FFFEDB03460

Fatal Run Error! 217
[Inferior 1 (process 1941) exited normally]
(gdb) 

Looking at the above, I believe the problem is probably in the intro executable itself.

**Comment by nukebloodaxe** [comment]
Looking into this further with the new build, running intro on its own:
(gdb) run
Starting program: /home/nukebloodaxe/ironseed_fpc/intro 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff0033700 (LWP 1373)]
[Thread 0x7ffff0033700 (LWP 1373) exited]
[New Thread 0x7ffff0033700 (LWP 1374)]
[New Thread 0x7fffef2e5700 (LWP 1375)]
[New Thread 0x7fffeeae4700 (LWP 1376)]
[New Thread 0x7fffed1e5700 (LWP 1377)]
[New Thread 0x7fffec9e4700 (LWP 1378)]
[Thread 0x7fffeeae4700 (LWP 1376) exited]
[New Thread 0x7fffcffff700 (LWP 1379)]
[New Thread 0x7fffcf7fe700 (LWP 1380)]

Thread 4 "intro" received signal SIGFPE, Arithmetic exception.
[Switching to Thread 0x7fffef2e5700 (LWP 1375)]
0x00007fffedb03460 in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so

Looks to be a rendering problem with the software rasteriser.  Remembering what happens in Python, that can be as simple as passing a float when an int is expected during pixel manipulation of a surface.  (The division by 0 is probably a float being converted to an int, and then the int is 0.)

**Comment by mnalis** [comment]
Hm, interesting that it does not produce line number when compiled with debug (`fpc -g -gl`). But probably because it does not happen in pascal (which in test fails with `Runtime error 200` for both `integer` and `real` divide-by-zero instead of your `EDivByZero` but in some other (C) thread. I cannot reproduce that in my `kvm` virtual machine.

- You could try to do `break fpc_raiseexception` before `run` in `gdb`, and then `thread apply all bt` - that usually worked for me to get trace in gdb (if fpc error handler got invoked).
- You could also skip intro by running `./main /playseed` directly to see if it is only intro that is affected.
- You could try to add `-DNO_OGL` to `cflags` line in` Makefile`, and also remove `-k-lGL -k-lGLU` from `p_link` in order to force SDL-only code (skipping OpenGL and thus 3D rendering code completely, hopefully including swrast_dri.so too)

BTW,  which fpc and gcc versions are you using there?

**Comment by nukebloodaxe** [comment]
Removing the compiler flags from plink and cflags resulted in a copy which runs.  So it's probably a problem with the VirtualBox OpenGL support in their driver at this moment (it has worked in the past, so this is something new.)

I did a test with the flags included and running main with the playseed switch, which resulted in the same crash problem from earlier, so it's the renderer in VB.

Debian 10
GCC version: 4:8.0.3-1
fpc version: 3.0.4+dfsg-22 [2019/01/24] for x86_64

**Comment by mnalis** [comment]
Or, as you say, it might be a bug in OpenGL support in Ironseed, which gets ignored on real 3D hardware, but triggers a fault in `swrast_dri`. 

If I manage to reproduce it (need to free some disk space first to install virtualbox, or maybe I can force KVM I already have to use same renderer?), I'd try commenting out OpenGL sections (searching `NO_OGL` in `c_utils.c`) until it starts to work, and then add some debug `printf`s before openGL calls which case the crash to find what exactly triggers it. I'd also probably need to learn a little OpenGL first too, so it can be a while until I decide to try to tackle this.

**Comment by mnalis** [comment]
I've managed to reproduce it in kvm. `break fpc_raiseexception` and  `thread apply all bt` in `gdb` showed me that it is failing in thread that is neither the main one which runs pascal, neither the `handle_keys()` thread. So it must be failing in `video_output()` thread. And it does - between `glBegin()` and `#endif`. If I comment that out, it no longer crashes (but also does not display anything in the window).

Playing around that part of the code (changing `0.0` to `0.1` and `1.0` to `0.8`, and adding several debug `write()` calls) makes it work sporadically.  But only changed values, or only added debug does not help.

So I guess it is special case of our buggy interaction of Threads with SDL / OpenGL, as documented in https://github.com/mnalis/ironseed_fpc/issues/25. Real fix would be learning how to use threads correctly in such cases. If some kludge with `SDL_Delay()` could make it work remains to be seen, but I really dislike such "solutions"...

**Comment by mnalis** [comment]
This seems to be the fix for EDivByZero in software OpenGL - This version runs normally under KVM!

 See  https://wiki.freepascal.org/Vulkan "Similar to OpenGL apps, the float-point exceptions should be turned off"
 and original bug https://bugs.freepascal.org/view.php?id=7570
 and discussion at https://forum.lazarus.freepascal.org/index.php?topic=36309.0

 Also, looking at fpc sources in debian at:
 `fpc-3.0.4+dfsg/fpcsrc/packages/opengl/src/gl.pp` there should be workaround for x86; but it seems that including "sysutils" overrides that workaround.

Now I just need to implement it in the game itself...

**Comment by mnalis** [comment]
Done! should be working now...
