### ISSUE TITLE
Psy Eval colour/animation issue

### ISSUE THREAD

**Issue by nukebloodaxe** [mnalis/ironseed_fpc#37]
In the Psychometric manipulation chamber, the evaluate button will open the panel to show the bio-rhythm of the crew member concerned.  At the moment, instead of showing a pulse like a heart monitor, it is showing a very hard to see grey line.  I suspect the colour palette routine is not cycling.  I also note the crew stat bars are pulsing, when they should be solid red.  The coloured stat lines being vertically orientated makes sense, and should remain vs the original behaviour:

Current behaviour:
![image](https://user-images.githubusercontent.com/13254225/89727167-6bee5900-da76-11ea-8aa7-c3bc44dc6557.png)

Expected Behaviour:
![image](https://user-images.githubusercontent.com/13254225/89727257-03ec4280-da77-11ea-971d-869abdaff8a3.png)

**Comment by mnalis** [comment]
- The _grey instead of red heart-pulse_ indeed looks like a bug. Although the bug is also in ironseed.net version, it can be seen for example in `savegame5`, where it is also dark grey, but after aliens are spotted few seconds later and you get alerted, pallete gets updated, and it is correct red afterwards. I'll look into fixing that part.

- about _"crew stat bars are pulsing, when they should be solid red"_, is that DOS screenshot from your old commercial release (1.10) ? I think that is expected behaviour also present in ironseed.net release 1.20.0016. `Documents/version.txt` (even going only as far back as 1.20.0002) mentions a lot of changes in crew psy stats, and there might be more between 1.10 and 1.20.
There are not only 3 solid red lines now, but 3 pairs (6 lines), and upper part of each pair is pulsing red and can be different that the lower part (which is solid and in psychotropic enhancement chamber color). This is normal and reflects updates in game logic (for example, "sanity" is now just related to "emotional", not being the same as I guess they were in 1.10).

This is how it looks in latest 37fffc76b64462874ac2b22b50d2969f8673c7a3:

![linux-fpc_0_0_9](https://user-images.githubusercontent.com/156656/89731170-3ed58280-da45-11ea-8ca3-7e66a4dbbc24.png)

and this is how it looks from latest [ironseed.net](http://ironseed.net/) release [ironseed-v1.20.0016-2013-03-17.zip](http://ironseed.net/ironseed-v1.20.0016-2013-03-17.zip)
![dos-idling-savegame](https://user-images.githubusercontent.com/156656/89731184-4a28ae00-da45-11ea-8b27-4ed0094835d6.png) in dosbox

**Comment by mnalis** [comment]
Also mentioned in `Documents/todo.txt`: 

```
psychometry:
        fix colours of biorhythm chart
```
