### ISSUE TITLE
not getting Sengzhac log?

### ISSUE THREAD

**Issue by mnalis** [mnalis/ironseed_fpc#52]
I've stumbled upon Zamiu system ( 51.4,9.9,174.3 ) and talked to Sengzhac about their homeworld and they also said to me this coordinates before attacking... but I never got the following log:

> @0 SENGZHAC
>  The references left to us in the first data buoy in no way exaggerated the ^Sengzhac^. We found them to be single mindedly cold and calculating just as the buoy described. A hive mentality pervades them. Because of this they claim a higher morality. They feel justified eliminating anything that might come between them and their precious "God's Eye".
>  Their fanaticism does, however, betray a note of fear. Whatever the God's Eye is, it must be enormously powerful to disturb such a stalwart race.
> ##
> Home World = Zamiu (51.4,9.9,174.3)

should it happen like this? or will game be unplayable afterwards?

**Comment by nukebloodaxe** [comment]
This particular system seems to use an event flag list, over my end I've made this an array of flags, but given the log is not firing off here I'd think that a check is not occurring when it should (could be a race condition.)  I note the "@0", which means it should be a first-run flag that needs no pre-conditions except an encounter flag for the race "SENGZHAC".    In theory, because you received the coordinates, it shouldn't be a problem.

The sengcon1.txt reveals that there's not too much going on with the flag system, so it'd be relatively okay.    Looking in event.txt, it would seem that it's safe enough there as well (I'm looking over this quickly though, so I may miss something.)

**Comment by mnalis** [comment]
It seems at one time game underwent major event/logs system change. Previously, all was kept in `ship.events[]`, and later it moved to `events[]`, `logs[]` and `logpending[]` (in addition to compatibility `ship.events[]` !). However, new code ignored value `0` for `event(0)` call, and that is related to `SENGZHAC` as seen in `Data_Generators/makedata/logs.txt`

**Comment by mnalis** [comment]
savegame should be ok, as next time we meet Sengzhac, we will get the log
